import type { ModeConfig } from '../types'

export const MODES: ModeConfig[] = [
  {
    id: 'plan',
    label: 'Plan Mode',
    shortLabel: 'Plan',
    description: 'Set up your project brief — site, typology, constraints, and goals.',
    shortDescription: 'Set up your brief',
    icon: 'map',
    color: '#E8607A',
    softColor: '#FFE4EC',
  },
  {
    id: 'help',
    label: 'Help Mode',
    shortLabel: 'Help',
    description: 'Bring a specific design problem and get structured approaches.',
    shortDescription: 'Solve a problem',
    icon: 'life-buoy',
    color: '#5B8DEF',
    softColor: '#DBEAFE',
  },
  {
    id: 'critic',
    label: 'Critic Mode',
    shortLabel: 'Critic',
    description: 'Simulate a design jury — get rigorous, adaptive feedback.',
    shortDescription: 'Jury simulation',
    icon: 'shield',
    color: '#E88B5E',
    softColor: '#FDE8D8',
  },
  {
    id: 'research',
    label: 'Research Mode',
    shortLabel: 'Research',
    description: 'Explore typologies, precedents, materials, and theory.',
    shortDescription: 'Explore & learn',
    icon: 'book-open',
    color: '#9B6FE8',
    softColor: '#E8DEF8',
  },
  {
    id: 'writing',
    label: 'Brief & Writing',
    shortLabel: 'Writing',
    description: 'Turn rough ideas into polished concept statements and descriptions.',
    shortDescription: 'Polish your text',
    icon: 'file-text',
    color: '#4CAF82',
    softColor: '#D1FAE5',
  },
  {
    id: 'program',
    label: 'Program Mode',
    shortLabel: 'Program',
    description: 'Build space lists, adjacencies, and circulation logic.',
    shortDescription: 'Space planning',
    icon: 'layout-grid',
    color: '#F5A623',
    softColor: '#FEF3C7',
  },
  {
    id: 'devils-advocate',
    label: "Devil's Advocate",
    shortLabel: "Devil's Adv.",
    description: "Stress-test your decisions — defend your ideas or rethink them.",
    shortDescription: 'Stress-test ideas',
    icon: 'swords',
    color: '#E8607A',
    softColor: '#FFE4EC',
  },
]
